myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^mysite/', include('mysite.urls')),
    url(r'^admin/', admin.site.urls),
    url('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.urls import path,include
from . import views

app_name = "mysite"

urlpatterns = [
    path('', views.index,name="index"),
    #Schedule
    #---------------------------------------------------------------------------------------------------------------------------------
    path('mycalendar/', views.MyCalendar.as_view(), name='mycalendar'),
    path('mycalendar/<int:year>/<int:month>/<int:day>/', views.MyCalendar.as_view(), name='mycalendar'),
    path('month/', views.MonthCalendar.as_view(), name='month'),
    path('month/<int:year>/<int:month>/', views.MonthCalendar.as_view(), name='month'),
    path('week/', views.WeekCalendar.as_view(), name='week'),
    path('week/<int:year>/<int:month>/<int:day>/', views.WeekCalendar.as_view(), name='week'),
    path('week_with_schedule/', views.WeekWithScheduleCalendar.as_view(), name='week_with_schedule'),
    path('week_with_schedule/<int:year>/<int:month>/<int:day>/',views.WeekWithScheduleCalendar.as_view(),name='week_with_schedule'),
    path('month_with_schedule/',views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'),
    path('month_with_schedule/<int:year>/<int:month>/',views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'),
    #Info
    #---------------------------------------------------------------------------------------------------------------------------------
    path("info_top/",views.info_top,name='info_top'),
    path('info_new/',views.info_new,name = "info_new"),
    path('info_edit/<int:num>',views.info_edit,name = "info_edit"),
    path('info_edit_comp/',views.info_edit_comp,name = "info_edit_comp"),
    path('info_delete/<int:num>',views.info_delete,name = "info_delete"),
    path("info_detail/<int:num>",views.info_detail,name='info_detail'),


    #Todo
    #---------------------------------------------------------------------------------------------------------------------------------
    path('todo_new/',views.todo_new,name = "todo_new"),
    path('todo_edit/<int:num>',views.todo_edit,name = "todo_edit"),
    path('todo_delete/<int:num>',views.todo_delete,name = "todo_delete"),
    path('todo_status/<int:num>',views.todo_status,name = "todo_status"),
    path('todo_hist/',views.todo_hist,name="todo_hist"),
    path('todo_top/',views.todo_top,name="todo_top"),
    path('todo_detail/<int:num>',views.todo_detail,name="todo_detail"),
    path('create_itemgroup/',views.create_itemgroup,name="create_itemgroup"),
    path('todo_group/',views.todo_group,name="todo_group"),
    path('todo_groupdetail/<int:num>',views.todo_groupdetail,name="todo_groupdetail"),
    path('todo_comp/',views.todo_comp,name = "todo_comp"),

    
    #FileUpload
    #---------------------------------------------------------------------------------------------------------------------------------
    path('upload/',views.file_upload,name="file_upload"),
    path('category/',views.file_category,name="file_category"),
    path('category_comp/',views.category_comp,name="category_comp"),
    path('file_detail/<int:num>',views.file_detail,name="file_detail"),
    path('file_delete/<int:num>',views.file_delete,name="file_delete"),
    path('filedelete_comp/',views.filedelete_comp,name="filedelete_comp"),
    path('file_comp/',views.filedelete_comp,name="file_comp"),

    #Mail
    #---------------------------------------------------------------------------------------------------------------------------------
    path('mail_top/',views.mail_top,name="mail_top"),

    #Accounting
    #---------------------------------------------------------------------------------------------------------------------------------
    path('accounting_top/',views.accounting_top,name="accounting_top"),



]

mysite/forms.py
from django import forms
from .models import User,Info,Todo,Schedule,ItemGroup,File
import bootstrap_datepicker_plus as datetimepicker
import calendar
from collections import deque




#Infoのフォーム
class InfoForm(forms.ModelForm):
    class Meta:
        model = Info
        fields = ['title','content','sub_content']

#Todoのフォーム
class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ['title','content','deadline','group']
        widgets = {
            'deadline': datetimepicker.DatePickerInput(
                format='%Y-%m-%d',
                options={
                    'locale': 'ja',
                    'dayViewHeaderFormat': 'YYYY- MMMM',
                }
            )}

#関連案件のグループ作成フォーム
class GroupForm(forms.ModelForm):
    class Meta:
        model = ItemGroup
        fields = ['title',"content"]


#関連案件のグループ選択フォーム
class GroupSelectForm(forms.Form):
    def __init__(self,*args,**kwargs):
        super(GroupSelectForm,self).__init__(*args,**kwargs)
        self.fields['group'] = forms.ChoiceField(choices=[('-','-')] + [(item.title,item.title)\
        for item in ItemGroup.objects.all()],)






#ファイルアップロードフォーム
class FileUploadForm(forms.Form):
    file_data = forms.FileField()





#スケジュール管理
class BS4ScheduleForm(forms.ModelForm):
    """Bootstrapに対応するためのModelForm"""

    class Meta:
        model = Schedule
        fields = ('summary', 'description', 'start_time', 'end_time')
        widgets = {
            'summary': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
            }),
            'start_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'end_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
        }

    def clean_end_time(self):
        start_time = self.cleaned_data['start_time']
        end_time = self.cleaned_data['end_time']
        if end_time <= start_time:
            raise forms.ValidationError(
                '終了時間は、開始時間よりも後にしてください'
            )
        return end_time

mysite/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import User,Info,Todo,Schedule,ItemGroup,File
from .forms import InfoForm,TodoForm,BS4ScheduleForm,GroupSelectForm,GroupForm,FileUploadForm
from . import mixins
import datetime
from django.views import generic
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

#base
def base(request):
    return render(request,'mysite/base.html')



#info
#-----------------------------------------------------------------------------------------------------
@login_required
def index(request):
    infolist = Info.objects.all().order_by("-pub_date")[0:5]
    todolist = Todo.objects.filter(status = 0).order_by("deadline")[0:5]
    login_user = request.user
    params ={
        "infolist":infolist,
        'todolist':todolist,
        'login_user':login_user,
    }
    return render(request,"mysite/index.html",params)


@login_required
def info_top(request):
    infolist = Info.objects.all()
    params = {
    'infolist':infolist,
    }
    return render(request,'mysite/info/top.html',params)


@login_required
def info_new(request):
    info_obj = Info()
    params = {
    "InfoForm":InfoForm}
    if (request.method =="POST"):
        title = request.POST["title"]
        content = request.POST["content"]
        sub_content = request.POST["sub_content"]
        owner = request.user
        info = Info(owner = owner,content = content,title = title,sub_content = sub_content)
        info.save()
        params = {
        "title":title,
        'content':content,
        'sub_content':sub_content,
        }
        return render(request,'mysite/info/edit_comp.html',params)

    return render(request,'mysite/info/new.html',params)


@login_required
def info_detail(request,num):
    info = Info.objects.get(id = num)
    params = {
    'info':info,
    }
    return render(request,"mysite/info/detail.html",params)

@login_required
def info_edit_comp(request):
    return render(request,"mysite/info/edit_comp.html")


@login_required
def info_edit(request,num):
    obj = Info.objects.get(id = num)
    if request.method == "POST":
        info = InfoForm(request.POST,instance=obj)
        info.save()
        title = request.POST["title"]
        content = request.POST["content"]
        sub_content = request.POST["sub_content"]
        param = {
        "title":title,
        'content':content,
        'sub_content':sub_content,
        }
        return redirect(to = "mysite:info_edit_comp")
    params = {
    'title':"Infoを編集します",
    "id":num,
    "form":InfoForm(instance=obj)
    }
    return render(request,"mysite/info/edit.html",params)


@login_required
def info_edit_comp(request):
    return render(request,"mysite/info/edit_comp.html")



@login_required
def info_delete(request,num):
    info = Info.objects.get(id = num)
    if(request.method == "POST"):
        info.delete()
        return redirect(to = "mysite:info_edit_comp")
    params = {
        'title':"以下の項目を削除します",
        "id":num,
        "info":info,
    }
    return render(request,"mysite/info/delete.html",params)



#Todo
#-----------------------------------------------------------------------------------------------------

#新規案件登録
@login_required
def todo_new(request):
    todo_obj = Todo()
    params = {
    "TodoForm":TodoForm,
    "GroupSelectForm":GroupSelectForm()}
    if (request.method =="POST"):
        title = request.POST["title"]
        content = request.POST["content"]
        deadline = request.POST["deadline"]
        group = request.POST["group"]
        if group == '':
            owner = request.user
            todo = Todo(owner = owner,content = content,title = title,deadline = deadline)
            todo.save()
        else:
            sel_group = ItemGroup.objects.get(id = group)
            owner = request.user
            todo = Todo(owner = owner,content = content,title = title,deadline = deadline,group=sel_group)
            todo.save()

        params = {
        "title":title,
        'content':content,
        'deadline': deadline,
        }
        return render(request,'mysite/todo/comp.html',params)

    return render(request,'mysite/todo/new.html',params)


@login_required
def todo_edit(request,num):
        obj = Todo.objects.get(id = num)
        if request.method == "POST":
            todo = TodoForm(request.POST,instance=obj)
            todo.save()
            title = request.POST["title"]
            content = request.POST["content"]
            deadline = request.POST["deadline"]
            param = {
            "title":title,
            'content':content,
            'deadline':deadline,
            }
            return redirect(to = "mysite:todo_comp")
        params = {
        'title':"Todoを編集します",
        "id":num,
        "form":TodoForm(instance=obj)
        }
        return render(request,"mysite/todo/edit.html",params)



@login_required
def todo_delete(request,num):
    todo = Todo.objects.get(id = num)
    if(request.method == "POST"):
        todo.delete()
        return redirect(to = "mysite:todo_comp")
    params = {
        'title':"以下の項目を削除します",
        "id":num,
        "obj":todo,
    }
    return render(request,"mysite/todo/delete.html",params)



@login_required
def todo_status(request,num):
    todo = Todo.objects.get(id = num)
    if(request.method == "POST"):
        if(todo.status==0):
            todo.status = 1
            todo.save()
            return redirect(to = "mysite:todo_comp")
        else:
            todo.status = 0
            todo.save()
            return redirect(to = "mysite:todo_comp")
    params = {
        'title':"案件ステータスを変更します",
        "id":num,
        "obj":todo,
    }
    return render(request,"mysite/todo/status_change.html",params)



@login_required
def todo_comp(request):
    return render(request,"mysite/todo/comp.html")



@login_required
def todo_hist(request):
    todolist = Todo.objects.all().filter(status = 1)
    params = {
    "title":"完了案件一覧",
    'todolist':todolist,
    }
    return render(request,"mysite/todo/hist.html",params)



@login_required
#未完了案件一蘭の表示
def todo_top(request):
    todolist = Todo.objects.all().filter(status = 0)
    params = {
    "title":"未完了案件一覧",
    'todolist':todolist,
    }
    return render(request,"mysite/todo/top.html",params)


@login_required
#案件詳細の表示
def todo_detail(request,num):
    todo = Todo.objects.get(id = num)
    params = {
    "title":"案件詳細",
    'todo':todo,
    }
    return render(request,"mysite/todo/detail.html",params)



@login_required
#新規案件グループの作成
def create_itemgroup(request):
    item_group = ItemGroup()
    params = {
    "GroupForm":GroupForm}
    if (request.method =="POST"):
        title = request.POST["title"]
        content = request.POST["content"]
        owner = request.user
        item_group= ItemGroup(owner = owner,content = content,title = title)
        item_group.save()
        params = {
        "title":title,
        'content':content,
        }
        return render(request,'mysite/todo/comp.html',params)

    return render(request,'mysite/todo/create_group.html',params)


@login_required
#案件グループ一覧の表示
def todo_group(request):
    grouplist = ItemGroup.objects.all().filter()
    params ={
    'title':'案件グループ一覧',
    'grouplist':grouplist,
    }
    return render(request,'mysite/todo/group.html',params)


@login_required
#案件グループに表示されている案件一覧の表示
def todo_groupdetail(request,num):
    todolist = Todo.objects.filter(id = num)
    #todolist = Todo.objects.filter(group = group)
    params = {
    "todolist":todolist
    }
    return render(request,"mysite/todo/group_detail.html",params)





@login_required
def file_category(request):

    filelist = File.objects.all()
    params = {
    'filelist':filelist
    }
    return render(request,'mysite/upload/category.html',params)



def file_upload(request):
    params = {
    "FileUploadForm":FileUploadForm,
    }
    if request.method == 'POST':
        form = FileUploadForm(request.POST, request.FILES)
        if not form.is_valid():
            raise ValueError('invalid form')

        file = File()
        file.file = form.cleaned_data['file_data']
        file.save()
        input_data = file.return_file()
        return redirect(to = 'mysite:category_comp')
    return render(request,'mysite/upload/upload.html',params)

@login_required
def category_comp(request):
    return render(request,"mysite/upload/comp.html")

@login_required
def file_detail(request,num):
    file = File.objects.all().filter(id = num)
    file_url = File.objects.get(id=num)
    #file_url = file_url.return_fileurl()
    params = {
    'file':file,
    'file_url':file_url,
    }
    return render(request,'mysite/upload/file_detail.html',params)

@login_required
def file_delete(request,num):
    file = File.objects.get(id = num)
    if(request.method == "POST"):
        file.delete()
        return redirect(to = "mysite:file_comp")
    params = {
        'title':"以下の項目を削除します",
        "file":file,

    }
    return render(request,"mysite/upload/file_delete.html",params)

@login_required
def filedelete_comp(request):
    return render(request,"mysite/upload/comp.html")




#メール
#-----------------------------------------------------------------------------------------------------

@login_required
def mail_top(request):
    return render(request,'mysite/mail/top.html')




#経費精算
#-----------------------------------------------------------------------------------------------------
@login_required
def accounting_top(request):
    return render(request,'mysite/accounting/top.html')









#スケジュール
#-----------------------------------------------------------------------------------------------------


class MonthCalendar(LoginRequiredMixin,mixins.MonthCalendarMixin, generic.TemplateView):
    """月間カレンダーを表示するビュー"""

templates/mysite/upload/category.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static "assets/img/apple-icon.png" %}">
    <link rel="icon" type="image/png" href="{% static "assets/img/favicon.png" %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>J&C Portal</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <!-- CSS Files -->
    <link href="{% static "assets/css/bootstrap.min.css" %}" rel="stylesheet" />
    <link href="{% static "assets/css/now-ui-dashboard.css" %}"?v=1.0.1 rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href='{% static "assets/demo/demo.css" %}' rel="stylesheet" />
    <link href='{% static "css/portal.css" %}' rel="stylesheet" />
</head>

<body class="">
    <div class="wrapper ">
        <div class="sidebar" data-color="orange">
            <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
    <div class="logo">
        <a href="{% url "mysite:index" %}" class="simple-text logo-normal">
            J&C Portal
        </a>
    </div>
    <div class="sidebar-wrapper">
        <ul class="nav">
          <li>
              <a href="{% url "mysite:info_top" %}">
                  <i class="now-ui-icons design_app"></i>
                  <p>Info</p>
              </a>
          </li>
          <li >
              <a href="{% url "mysite:todo_top" %}">
                  <i class="now-ui-icons education_atom"></i>
                  <p>Todo</p>
              </a>
          </li>
          <li >
              <a href="{% url "mysite:mycalendar" %}">
                  <i class="now-ui-icons location_map-big"></i>
                  <p>スケジュール</p>
              </a>
          </li>
          <li class="active">
              <a href="{% url "mysite:file_category" %}">
                  <i class="now-ui-icons ui-1_bell-53"></i>
                  <p>ファイルアップロード</p>
              </a>
          </li>
          <li>
              <a href="{% url "mysite:mail_top" %}">
                  <i class="now-ui-icons users_single-02"></i>
                  <p>メール</p>
              </a>
          </li>
          <li >
              <a href="{% url "mysite:accounting_top" %}">
                  <i class="now-ui-icons design_bullet-list-67"></i>
                  <p>経費精算</p>
              </a>
          </li>
          <li>
              <a href="{% url "logout" %}">
                  <i class="now-ui-icons text_caps-small"></i>
                  <p>ログアウト</p>
              </a>
          </li>
      </ul>
    </div>
        </div>
        <div class="main-panel">
            <!-- Navbar -->

            <div class="panel-header panel-header-sm">
            </div>
            <div class="content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">


                          <div class="folder">

                            {% for file in file_list %}
                            <a href='{% url "mysite:file_detail" file.id%}'>  <img class='folder'src="{% static "img/folder.jpg" %}" alt='' width="300" height='250'></a>
                            <a href='{% url "mysite:file_detail" file.id%}' class ='file_name'> {{file}} </a>
                            {% endfor %}


                            </div>


                                <div class="places-buttons">

                                    <div class="row">
                                        <div class="col-lg-8 ml-auto mr-auto">
                                            <div class="row">
                                                <div class="col-md-4">
                                                    <a  class="btn btn-primary btn-block" href='{% url "mysite:file_upload" %}'>ファイルアップロード</a>
                                                </div>
                                                <div class="col-md-4">
                                                    <a  class="btn btn-primary btn-block" href='{% url "mysite:info_top" %}'>記事一覧へ</a>
                                                </div>

                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
  </body>
  <!--   Core JS Files   -->
  <script src="{% static "assets/js/core/jquery.min.js" %}"></script>
  <script src="{% static "assets/js/core/bootstrap.min.js" %}"></script>
  <script src="{% static "assets/js/core/popper.min.js" %}"></script>
  <script src="{% static "assets/js/plugins/perfect-scrollbar.jquery.min.js" %}"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chart JS -->
  <script src="{% static "assets/js/plugins/chartjs.min.js" %}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static "assets/js/plugins/bootstrap-notify.js" %}"></script>
  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static "assets/js/now-ui-dashboard.js?v=1.0.1" %}"></script>
  <!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
  <script src="{% static "assets/demo/demo.js" %}"></script>

  </html>

templates/mysite/upload/category_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static "assets/img/apple-icon.png" %}">
    <link rel="icon" type="image/png" href="{% static "assets/img/favicon.png" %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>J&C Portal</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <!-- CSS Files -->
    <link href="{% static "assets/css/bootstrap.min.css" %}" rel="stylesheet" />
    <link href="{% static "assets/css/now-ui-dashboard.css" %}"?v=1.0.1 rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href='{% static "assets/demo/demo.css" %}' rel="stylesheet" />
    <link href='{% static "css/portal.css" %}' rel="stylesheet" />
</head>

<body class="">
    <div class="wrapper ">
        <div class="sidebar" data-color="orange">
            <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
    <div class="logo">
        <a href="{% url "mysite:index" %}" class="simple-text logo-normal">
            J&C Portal
        </a>
    </div>
    <div class="sidebar-wrapper">
        <ul class="nav">
          <li>
              <a href="{% url "mysite:info_top" %}">
                  <i class="now-ui-icons design_app"></i>
                  <p>Info</p>
              </a>
          </li>
          <li >
              <a href="{% url "mysite:todo_top" %}">
                  <i class="now-ui-icons education_atom"></i>
                  <p>Todo</p>
              </a>
          </li>
          <li >
              <a href="{% url "mysite:mycalendar" %}">
                  <i class="now-ui-icons location_map-big"></i>
                  <p>スケジュール</p>
              </a>
          </li>
          <li class="active">
              <a href="{% url "mysite:file_category" %}">
                  <i class="now-ui-icons ui-1_bell-53"></i>
                  <p>ファイルアップロード</p>
              </a>
          </li>
          <li>
              <a href="{% url "mysite:mail_top" %}">
                  <i class="now-ui-icons users_single-02"></i>
                  <p>メール</p>
              </a>
          </li>
          <li >
              <a href="{% url "mysite:accounting_top" %}">
                  <i class="now-ui-icons design_bullet-list-67"></i>
                  <p>経費精算</p>
              </a>
          </li>
          <li>
              <a href="{% url "logout" %}">
                  <i class="now-ui-icons text_caps-small"></i>
                  <p>ログアウト</p>
              </a>
          </li>
      </ul>
    </div>
        </div>
        <div class="main-panel">
            <!-- Navbar -->

            <div class="panel-header panel-header-sm">
            </div>
            <div class="content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">



                          <table class="fileblock">




                            {% for file in filelist %}


                                <td>
                            <a href='{% url "mysite:file_detail" file.id %}'>  <img class='folder'src="{% static "img/file.png" %}" alt='' width="200" height='200'></a>


                            <div class="filename">
                            <a href='{% url "mysite:file_detail" file.id %}' class ='file_name'> {{file.title}} </a>
                            </div>

                            </div>
                            {% endfor %}
                            </td>


                          </table>

                                <div class="places-buttons">

                                    <div class="row">
                                        <div class="col-lg-8 ml-auto mr-auto">
                                            <div class="row">
                                                <div class="col-md-4">
                                                    <a  class="btn btn-primary btn-block" href='{% url "mysite:info_top" %}'>記事一覧へ</a>
                                                </div>

                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
  </body>
  <!--   Core JS Files   -->
  <script src="{% static "assets/js/core/jquery.min.js" %}"></script>
  <script src="{% static "assets/js/core/bootstrap.min.js" %}"></script>
  <script src="{% static "assets/js/core/popper.min.js" %}"></script>
  <script src="{% static "assets/js/plugins/perfect-scrollbar.jquery.min.js" %}"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chart JS -->
  <script src="{% static "assets/js/plugins/chartjs.min.js" %}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static "assets/js/plugins/bootstrap-notify.js" %}"></script>
  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static "assets/js/now-ui-dashboard.js?v=1.0.1" %}"></script>
  <!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
  <script src="{% static "assets/demo/demo.js" %}"></script>

  </html>