myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^mysite/', include('mysite.urls')),
    url(r'^admin/', admin.site.urls),
    url('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.urls import path,include
from . import views

app_name = "mysite"

urlpatterns = [
    path('', views.index,name="index"),
    #Schedule
    #---------------------------------------------------------------------------------------------------------------------------------
    path('mycalendar/', views.MyCalendar.as_view(), name='mycalendar'),
    path('mycalendar/<int:year>/<int:month>/<int:day>/', views.MyCalendar.as_view(), name='mycalendar'),
    path('month/', views.MonthCalendar.as_view(), name='month'),
    path('month/<int:year>/<int:month>/', views.MonthCalendar.as_view(), name='month'),
    path('week/', views.WeekCalendar.as_view(), name='week'),
    path('week/<int:year>/<int:month>/<int:day>/', views.WeekCalendar.as_view(), name='week'),
    path('week_with_schedule/', views.WeekWithScheduleCalendar.as_view(), name='week_with_schedule'),
    path('week_with_schedule/<int:year>/<int:month>/<int:day>/',views.WeekWithScheduleCalendar.as_view(),name='week_with_schedule'),
    path('month_with_schedule/',views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'),
    path('month_with_schedule/<int:year>/<int:month>/',views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'),
    #Info
    #---------------------------------------------------------------------------------------------------------------------------------
    path("info_top/",views.info_top,name='info_top'),
    path('info_new/',views.info_new,name = "info_new"),
    path('info_edit/<int:num>',views.info_edit,name = "info_edit"),
    path('info_edit_comp/',views.info_edit_comp,name = "info_edit_comp"),
    path('info_delete/<int:num>',views.info_delete,name = "info_delete"),
    path("info_detail/<int:num>",views.info_detail,name='info_detail'),


    #Todo
    #---------------------------------------------------------------------------------------------------------------------------------
    path('todo_new/',views.todo_new,name = "todo_new"),
    path('todo_edit/<int:num>',views.todo_edit,name = "todo_edit"),
    path('todo_delete/<int:num>',views.todo_delete,name = "todo_delete"),
    path('todo_status/<int:num>',views.todo_status,name = "todo_status"),
    path('todo_hist/',views.todo_hist,name="todo_hist"),
    path('todo_top/',views.todo_top,name="todo_top"),
    path('todo_detail/<int:num>',views.todo_detail,name="todo_detail"),
    path('create_itemgroup/',views.create_itemgroup,name="create_itemgroup"),
    path('todo_group/',views.todo_group,name="todo_group"),
    path('todo_groupdetail/<int:num>',views.todo_groupdetail,name="todo_groupdetail"),
    path('todo_comp/',views.todo_comp,name = "todo_comp"),

    
    #FileUpload
    #---------------------------------------------------------------------------------------------------------------------------------
    path('upload/',views.file_upload,name="file_upload"),
    path('category/',views.file_category,name="file_category"),
    path('category_comp/',views.category_comp,name="category_comp"),
    path('file_detail/<int:num>',views.file_detail,name="file_detail"),
    path('file_delete/<int:num>',views.file_delete,name="file_delete"),
    path('filedelete_comp/',views.filedelete_comp,name="filedelete_comp"),
    path('file_comp/',views.filedelete_comp,name="file_comp"),

    #Mail
    #---------------------------------------------------------------------------------------------------------------------------------
    path('mail_top/',views.mail_top,name="mail_top"),

    #Accounting
    #---------------------------------------------------------------------------------------------------------------------------------
    path('accounting_top/',views.accounting_top,name="accounting_top"),



]

mysite/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import datetime
from django.utils import timezone
import os

#独自ユーザーテーブル
class User(AbstractUser):
    pass

#ファイルテーブル
class File(models.Model):

    file = models.FileField(upload_to='media/')

    def return_file(self):
        return self.file.url

#インフォテーブル
class Info(models.Model):
    owner = models.ForeignKey("User",on_delete=models.CASCADE,related_name="info_owner")
    title = models.CharField(max_length = 100)
    content = models.TextField(max_length=1000)
    sub_content = models.TextField(max_length=200)
    pub_date = models.DateField(default=timezone.now)

    def __str__(self):
        return str(self.pub_date) + str(self.content) + "(" + str(self.owner) + ")"

    class Meta:
        ordering = ('-pub_date',)

#Todoテーブル
class Todo(models.Model):
    owner = models.ForeignKey("User",on_delete=models.CASCADE,related_name="todo_owner")
    pub_date = models.DateField(default=timezone.now)
    deadline = models.DateField()
    title = models.CharField(max_length = 100)
    content = models.TextField(max_length=1000)
    status = models.BooleanField(default=False)
    group = models.ForeignKey("ItemGroup",on_delete=models.CASCADE,null=True,blank=True)


    def __str__(self):
        return "期日:" + str(self.deadline) +str(self.content) + "(" + str(self.owner) + ")"

    class Meta:
        ordering = ('deadline',)

#スケジュールテーブル
class Schedule(models.Model):
    #owner = models.ForeignKey("User",on_delete=models.CASCADE,related_name="schedule_owner")
    summary = models.CharField('概要', max_length=50)
    description = models.TextField('詳細な説明', blank=True)
    start_time = models.TimeField('開始時間', default=datetime.time(7, 0, 0))
    end_time = models.TimeField('終了時間', default=datetime.time(7, 0, 0))
    date = models.DateField('日付')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.summary



class ItemGroup(models.Model):
    owner = models.ForeignKey("User",on_delete=models.CASCADE,related_name="itemgroup_owner")
    title = models.CharField(max_length = 100)
    content = models.TextField(max_length=1000,null=True,blank=True)

    def __str__(self):
        return str(self.title)

mysite/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import User,Info,Todo,Schedule,ItemGroup,File
from .forms import InfoForm,TodoForm,BS4ScheduleForm,GroupSelectForm,GroupForm,FileUploadForm
from . import mixins
import datetime
from django.views import generic
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

#base
def base(request):
    return render(request,'mysite/base.html')



#info
#-----------------------------------------------------------------------------------------------------
@login_required
def index(request):
    infolist = Info.objects.all().order_by("-pub_date")[0:5]
    todolist = Todo.objects.filter(status = 0).order_by("deadline")[0:5]
    login_user = request.user
    params ={
        "infolist":infolist,
        'todolist':todolist,
        'login_user':login_user,
    }
    return render(request,"mysite/index.html",params)


@login_required
def info_top(request):
    infolist = Info.objects.all()
    params = {
    'infolist':infolist,
    }
    return render(request,'mysite/info/top.html',params)


@login_required
def info_new(request):
    info_obj = Info()
    params = {
    "InfoForm":InfoForm}
    if (request.method =="POST"):
        title = request.POST["title"]
        content = request.POST["content"]
        sub_content = request.POST["sub_content"]
        owner = request.user
        info = Info(owner = owner,content = content,title = title,sub_content = sub_content)
        info.save()
        params = {
        "title":title,
        'content':content,
        'sub_content':sub_content,
        }
        return render(request,'mysite/info/edit_comp.html',params)

    return render(request,'mysite/info/new.html',params)


@login_required
def info_detail(request,num):
    info = Info.objects.get(id = num)
    params = {
    'info':info,
    }
    return render(request,"mysite/info/detail.html",params)

@login_required
def info_edit_comp(request):
    return render(request,"mysite/info/edit_comp.html")


@login_required
def info_edit(request,num):
    obj = Info.objects.get(id = num)
    if request.method == "POST":
        info = InfoForm(request.POST,instance=obj)
        info.save()
        title = request.POST["title"]
        content = request.POST["content"]
        sub_content = request.POST["sub_content"]
        param = {
        "title":title,
        'content':content,
        'sub_content':sub_content,
        }
        return redirect(to = "mysite:info_edit_comp")
    params = {
    'title':"Infoを編集します",
    "id":num,
    "form":InfoForm(instance=obj)
    }
    return render(request,"mysite/info/edit.html",params)


@login_required
def info_edit_comp(request):
    return render(request,"mysite/info/edit_comp.html")



@login_required
def info_delete(request,num):
    info = Info.objects.get(id = num)
    if(request.method == "POST"):
        info.delete()
        return redirect(to = "mysite:info_edit_comp")
    params = {
        'title':"以下の項目を削除します",
        "id":num,
        "info":info,
    }
    return render(request,"mysite/info/delete.html",params)



#Todo
#-----------------------------------------------------------------------------------------------------

#新規案件登録
@login_required
def todo_new(request):
    todo_obj = Todo()
    params = {
    "TodoForm":TodoForm,
    "GroupSelectForm":GroupSelectForm()}
    if (request.method =="POST"):
        title = request.POST["title"]
        content = request.POST["content"]
        deadline = request.POST["deadline"]
        group = request.POST["group"]
        if group == '':
            owner = request.user
            todo = Todo(owner = owner,content = content,title = title,deadline = deadline)
            todo.save()
        else:
            sel_group = ItemGroup.objects.get(id = group)
            owner = request.user
            todo = Todo(owner = owner,content = content,title = title,deadline = deadline,group=sel_group)
            todo.save()

        params = {
        "title":title,
        'content':content,
        'deadline': deadline,
        }
        return render(request,'mysite/todo/comp.html',params)

    return render(request,'mysite/todo/new.html',params)


@login_required
def todo_edit(request,num):
        obj = Todo.objects.get(id = num)
        if request.method == "POST":
            todo = TodoForm(request.POST,instance=obj)
            todo.save()
            title = request.POST["title"]
            content = request.POST["content"]
            deadline = request.POST["deadline"]
            param = {
            "title":title,
            'content':content,
            'deadline':deadline,
            }
            return redirect(to = "mysite:todo_comp")
        params = {
        'title':"Todoを編集します",
        "id":num,
        "form":TodoForm(instance=obj)
        }
        return render(request,"mysite/todo/edit.html",params)



@login_required
def todo_delete(request,num):
    todo = Todo.objects.get(id = num)
    if(request.method == "POST"):
        todo.delete()
        return redirect(to = "mysite:todo_comp")
    params = {
        'title':"以下の項目を削除します",
        "id":num,
        "obj":todo,
    }
    return render(request,"mysite/todo/delete.html",params)



@login_required
def todo_status(request,num):
    todo = Todo.objects.get(id = num)
    if(request.method == "POST"):
        if(todo.status==0):
            todo.status = 1
            todo.save()
            return redirect(to = "mysite:todo_comp")
        else:
            todo.status = 0
            todo.save()
            return redirect(to = "mysite:todo_comp")
    params = {
        'title':"案件ステータスを変更します",
        "id":num,
        "obj":todo,
    }
    return render(request,"mysite/todo/status_change.html",params)



@login_required
def todo_comp(request):
    return render(request,"mysite/todo/comp.html")



@login_required
def todo_hist(request):
    todolist = Todo.objects.all().filter(status = 1)
    params = {
    "title":"完了案件一覧",
    'todolist':todolist,
    }
    return render(request,"mysite/todo/hist.html",params)



@login_required
#未完了案件一蘭の表示
def todo_top(request):
    todolist = Todo.objects.all().filter(status = 0)
    params = {
    "title":"未完了案件一覧",
    'todolist':todolist,
    }
    return render(request,"mysite/todo/top.html",params)


@login_required
#案件詳細の表示
def todo_detail(request,num):
    todo = Todo.objects.get(id = num)
    params = {
    "title":"案件詳細",
    'todo':todo,
    }
    return render(request,"mysite/todo/detail.html",params)



@login_required
#新規案件グループの作成
def create_itemgroup(request):
    item_group = ItemGroup()
    params = {
    "GroupForm":GroupForm}
    if (request.method =="POST"):
        title = request.POST["title"]
        content = request.POST["content"]
        owner = request.user
        item_group= ItemGroup(owner = owner,content = content,title = title)
        item_group.save()
        params = {
        "title":title,
        'content':content,
        }
        return render(request,'mysite/todo/comp.html',params)

    return render(request,'mysite/todo/create_group.html',params)


@login_required
#案件グループ一覧の表示
def todo_group(request):
    grouplist = ItemGroup.objects.all().filter()
    params ={
    'title':'案件グループ一覧',
    'grouplist':grouplist,
    }
    return render(request,'mysite/todo/group.html',params)


@login_required
#案件グループに表示されている案件一覧の表示
def todo_groupdetail(request,num):
    todolist = Todo.objects.filter(id = num)
    #todolist = Todo.objects.filter(group = group)
    params = {
    "todolist":todolist
    }
    return render(request,"mysite/todo/group_detail.html",params)





@login_required
def file_category(request):

    filelist = File.objects.all()
    params = {
    'filelist':filelist
    }
    return render(request,'mysite/upload/category.html',params)



def file_upload(request):
    params = {
    "FileUploadForm":FileUploadForm,
    }
    if request.method == 'POST':
        form = FileUploadForm(request.POST, request.FILES)
        if not form.is_valid():
            raise ValueError('invalid form')

        file = File()
        file.file = form.cleaned_data['file_data']
        file.save()
        input_data = file.return_file()
        return redirect(to = 'mysite:category_comp')
    return render(request,'mysite/upload/upload.html',params)

@login_required
def category_comp(request):
    return render(request,"mysite/upload/comp.html")

@login_required
def file_detail(request,num):
    file = File.objects.all().filter(id = num)
    file_url = File.objects.get(id=num)
    #file_url = file_url.return_fileurl()
    params = {
    'file':file,
    'file_url':file_url,
    }
    return render(request,'mysite/upload/file_detail.html',params)

@login_required
def file_delete(request,num):
    file = File.objects.get(id = num)
    if(request.method == "POST"):
        file.delete()
        return redirect(to = "mysite:file_comp")
    params = {
        'title':"以下の項目を削除します",
        "file":file,

    }
    return render(request,"mysite/upload/file_delete.html",params)

@login_required
def filedelete_comp(request):
    return render(request,"mysite/upload/comp.html")




#メール
#-----------------------------------------------------------------------------------------------------

@login_required
def mail_top(request):
    return render(request,'mysite/mail/top.html')




#経費精算
#-----------------------------------------------------------------------------------------------------
@login_required
def accounting_top(request):
    return render(request,'mysite/accounting/top.html')









#スケジュール
#-----------------------------------------------------------------------------------------------------


class MonthCalendar(LoginRequiredMixin,mixins.MonthCalendarMixin, generic.TemplateView):
    """月間カレンダーを表示するビュー"""

templates/mysite/schedule/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static "assets/img/apple-icon.png" %}">
    <link rel="icon" type="image/png" href="{% static "assets/img/favicon.png" %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>J&C Portal</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <!-- CSS Files -->
    <link href="{% static "assets/css/bootstrap.min.css" %}" rel="stylesheet" />
    <link href="{% static "assets/css/now-ui-dashboard.css" %}"?v=1.0.1 rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href='{% static "assets/demo/demo.css" %}' rel="stylesheet" />
    <link href='{% static "css/portal.css" %}' rel="stylesheet" />
</head>
<body>
  <div class="wrapper ">
      <div class="sidebar" data-color="orange">
          <!--
      Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
  -->
          <div class="logo">
              <a href="{% url "mysite:index" %}" class="simple-text logo-normal">
                  J&C Portal
              </a>
          </div>
          <div class="sidebar-wrapper">
              <ul class="nav">
                <li>
                    <a href="{% url "mysite:info_top" %}">
                        <i class="now-ui-icons design_app"></i>
                        <p>Info</p>
                    </a>
                </li>
                <li>
                    <a href="{% url "mysite:todo_top" %}">
                        <i class="now-ui-icons education_atom"></i>
                        <p>Todo</p>
                    </a>
                </li>
                <li class="active">
                    <a href="{% url "mysite:mycalendar" %}">
                        <i class="now-ui-icons location_map-big"></i>
                        <p>スケジュール</p>
                    </a>
                </li>
                <li>
                    <a href="{% url "mysite:file_category" %}">
                        <i class="now-ui-icons ui-1_bell-53"></i>
                        <p>ファイルアップロード</p>
                    </a>
                </li>
                <li>
                    <a href="{% url "mysite:mail_top" %}">
                        <i class="now-ui-icons users_single-02"></i>
                        <p>メール</p>
                    </a>
                </li>
                <li >
                    <a href="{% url "mysite:accounting_top" %}">
                        <i class="now-ui-icons design_bullet-list-67"></i>
                        <p>経費精算</p>
                    </a>
                </li>
                <li>
                    <a href="{% url "logout" %}">
                        <i class="now-ui-icons text_caps-small"></i>
                        <p>ログアウト</p>
                    </a>
                </li>
            </ul>
          </div>
      </div>
      </div>
      <div class="panel-header-s shecule-head" >
      </div>

<div class="container schedule" mt-3>
    {% block content %}{% endblock %}
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
{% block extrajs %}{% endblock %}
</body>
<!--   Core JS Files   -->
<script src="{% static "assets/js/core/jquery.min.js" %}"></script>
<script src="{% static "assets/js/core/bootstrap.min.js" %}"></script>
<script src="{% static "assets/js/core/popper.min.js" %}"></script>
<script src="{% static "assets/js/plugins/perfect-scrollbar.jquery.min.js" %}"></script>
<!--  Google Maps Plugin    -->
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!-- Chart JS -->
<script src="{% static "assets/js/plugins/chartjs.min.js" %}"></script>
<!--  Notifications Plugin    -->
<script src="{% static "assets/js/plugins/bootstrap-notify.js" %}"></script>
<!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{% static "assets/js/now-ui-dashboard.js?v=1.0.1" %}"></script>
<!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
<script src="{% static "assets/demo/demo.js" %}"></script>

</html>

templates/mysite/schedule/month.html
<a href="{% url 'mysite:mycalendar' month_previous.year month_previous.month month_previous.day %}">前月</a>
{{ month_current | date:"Y年m月" }}
<a href="{% url 'mysite:mycalendar' month_next.year month_next.month month_next.day %}">次月</a>

<table class="table" style="table-layout: fixed;">
    <thead>
    <tr>
        {% for w in week_names %}
            <th>{{ w }}</th>
        {% endfor %}
    </tr>
    </thead
    <tbody>
    {% for week in month_days %}
        <tr>
            {% for day in week %}
                {% if now == day %}
                    <td class="table-success">
                {% else %}
                    <td>
                {% endif %}

                <a href="{% url 'mysite:mycalendar' day.year day.month day.day %}">{{ day.day }}</a>
                </td>
            {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/mysite/schedule/mycalendar.html
{% extends 'mysite/schedule/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-3">
            {% include 'mysite/schedule/month.html' %}
            <hr>
            <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}"
                               class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-block">投稿</button>
            </form>
        </div>
        <div class="col-md-9">
            {% include 'mysite/schedule/week.html' %}
        </div>
    </div>
{% endblock %}


{% block extrajs %}
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
    <script>
        $(function () {
            // timedropper
            $("#id_start_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
            $("#id_end_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
        });
    </script>
{% endblock %}

templates/mysite/schedule/week.html
<a href="{% url 'mysite:mycalendar' week_previous.year week_previous.month  week_previous.day %}">前週</a>
{{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}
<a href="{% url 'mysite:mycalendar' week_next.year week_next.month  week_next.day %}">次週</a>

<table class="table" style="table-layout: fixed;">
    <tbody>
    <tr>
        {% for day in week_days %}
            {% if now == day %}
                <td class="table-success">
                    {% else %}
                <td>
            {% endif %}
        {% if week_first.month != day.month %}
            {{ day | date:"m/d" }}
        {% else %}
            {{ day.day }}
        {% endif %}
        </td>
        {% endfor %}
    </tr>
    <tr>
        {% for schedules in week_day_schedules.values %}
            <td>
                {% for s in schedules %}
                    {{ s.start_time }} - {{ s.end_time }}<br>
                    {{ s.summary }}<br>
                    {{ s.description | linebreaks }}
                {% endfor %}
            </td>
        {% endfor %}
    </tr>
    </tbody>
</table>